### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by bighammilad** [ah-Izadi/python#1]
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
between 2000 and 3200 (both included).
The numbers obtained should be printed in a comma-separated sequence on a single line.

**Comment by bighammilad** [comment]
Hints: 
Consider use range(#begin, #end) method

**Comment by ah-Izadi** [comment]
I did It

**Comment by bighammilad** [comment]
very well,
Do it in another way
with a list and join method

**Comment by bighammilad** [comment]
fine, and write a test for it please

**Comment by ah-Izadi** [comment]
done

**Comment by bighammilad** [comment]
fine, and write a test for it please

**Comment by ah-Izadi** [comment]
I have done it
